title: 波波今晚不加班
description: > # this means to ignore newlines until "baseurl:"
  不负韶华<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.boblv.cn" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Bob'
  last_name: 'Lv'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  boblvcn  
  email: boblv@boblv.cn
  vk_id: id201664979
  telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


